#!/usr/bin/env bash
# This file is auto-generated by @lark-apaas/fullstack-cli

set -uo pipefail

# Ensure the script always runs from the project root
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Configuration
LOG_DIR=${LOG_DIR:-logs}
DEV_LOG="${LOG_DIR}/dev.log"
MAX_RESTART_COUNT=${MAX_RESTART_COUNT:-10}
RESTART_DELAY=${RESTART_DELAY:-2}

# Process tracking
SERVER_PID=""
CLIENT_PID=""
PARENT_PID=$$
STOP_FLAG_FILE="/tmp/dev_sh_stop_$$"
CLEANUP_DONE=false

mkdir -p "${LOG_DIR}"

# Log event to dev.log with timestamp
log_event() {
  local level=$1
  local process_name=$2
  local message=$3
  local msg="[$(date '+%Y-%m-%d %H:%M:%S')] [${level}] [${process_name}] ${message}"
  echo "$msg"
  echo "$msg" >> "${DEV_LOG}"
}

# Check if PID is valid (positive integer and process exists)
is_valid_pid() {
  local pid=$1
  [[ -n "$pid" ]] && [[ "$pid" =~ ^[0-9]+$ ]] && [[ "$pid" -gt 0 ]] && kill -0 "$pid" 2>/dev/null
}

# Check if parent process is still alive
is_parent_alive() {
  kill -0 "$PARENT_PID" 2>/dev/null
}

# Check if should stop (parent exited or stop flag exists)
should_stop() {
  [[ -f "$STOP_FLAG_FILE" ]] || ! is_parent_alive
}

# Kill entire process tree (process and all descendants)
kill_tree() {
  local pid=$1
  local signal=${2:-TERM}

  # Get all descendant PIDs
  local children
  children=$(pgrep -P "$pid" 2>/dev/null) || true

  # Recursively kill children first
  for child in $children; do
    kill_tree "$child" "$signal"
  done

  # Kill the process itself
  if kill -0 "$pid" 2>/dev/null; then
    kill -"$signal" "$pid" 2>/dev/null || true
  fi
}

# Start a process with supervision
# $1: name
# $2: command
# $3: cleanup port for orphan processes (optional)
start_supervised_process() {
  local name=$1
  local cmd=$2
  local cleanup_port=${3:-""}
  local log_file="${LOG_DIR}/${name}.std.log"

  (
    local restart_count=0
    local child_pid=""
    local max_delay=60  # Maximum delay in seconds

    # Handle signals to kill child process tree
    trap 'if [[ -n "$child_pid" ]]; then kill_tree "$child_pid" TERM; fi' TERM INT

    while true; do
      # Check if we should stop (parent exited or stop flag)
      if should_stop; then
        log_event "INFO" "$name" "Process stopped (parent exited or user requested)"
        break
      fi

      # Start command in background and capture output with timestamps
      eval "$cmd" > >(
        while IFS= read -r line; do
          local msg="[$(date '+%Y-%m-%d %H:%M:%S')] [${name}] ${line}"
          echo "$msg"
          echo "$msg" >> "$log_file"
        done
      ) 2>&1 &
      child_pid=$!

      log_event "INFO" "$name" "Process started (PID: ${child_pid}): ${cmd}"

      # Wait for child to exit
      set +e
      wait "$child_pid"
      exit_code=$?
      set -e

      # Kill entire process tree to avoid orphans
      if [[ -n "$child_pid" ]]; then
        kill_tree "$child_pid" TERM
        sleep 0.5
        kill_tree "$child_pid" KILL
      fi
      child_pid=""

      # Cleanup orphan processes by port (for processes that escaped kill_tree)
      if [[ -n "$cleanup_port" ]]; then
        local orphan_pids
        orphan_pids=$(lsof -ti ":${cleanup_port}" 2>/dev/null) || true
        if [[ -n "$orphan_pids" ]]; then
          log_event "WARN" "$name" "Killing orphan processes on port ${cleanup_port}: $(echo $orphan_pids | tr '\n' ' ')"
          echo "$orphan_pids" | xargs kill -9 2>/dev/null || true
          sleep 0.5
        fi
      fi

      # Check if we should stop (parent exited or stop flag)
      if should_stop; then
        log_event "INFO" "$name" "Process stopped (parent exited or user requested)"
        break
      fi

      # Process exited unexpectedly, restart
      restart_count=$((restart_count + 1))

      if [[ $restart_count -ge $MAX_RESTART_COUNT ]]; then
        log_event "ERROR" "$name" "Max restart count (${MAX_RESTART_COUNT}) reached, giving up"
        break
      fi

      # Exponential backoff: delay = RESTART_DELAY * 2^(restart_count-1), capped at max_delay
      local delay=$((RESTART_DELAY * (1 << (restart_count - 1))))
      if [[ $delay -gt $max_delay ]]; then
        delay=$max_delay
      fi

      log_event "WARN" "$name" "Process exited with code ${exit_code}, restarting (${restart_count}/${MAX_RESTART_COUNT}) in ${delay}s..."
      sleep "$delay"
    done
  ) &
}

# Cleanup function
cleanup() {
  # Prevent multiple cleanup calls
  if [[ "$CLEANUP_DONE" == "true" ]]; then
    return
  fi
  CLEANUP_DONE=true

  log_event "INFO" "main" "Shutting down all processes..."

  # Create stop flag to signal child processes
  touch "$STOP_FLAG_FILE"

  # Kill entire process trees (TERM first)
  for pid in $SERVER_PID $CLIENT_PID; do
    if is_valid_pid "$pid"; then
      log_event "INFO" "main" "Stopping process tree (PID: ${pid})"
      kill_tree "$pid" TERM
    fi
  done

  # Kill any remaining background jobs
  local bg_pids
  bg_pids=$(jobs -p 2>/dev/null) || true
  if [[ -n "$bg_pids" ]]; then
    for pid in $bg_pids; do
      kill_tree "$pid" TERM
    done
  fi

  # Wait for processes to terminate
  sleep 1

  # Force kill if still running
  for pid in $SERVER_PID $CLIENT_PID; do
    if is_valid_pid "$pid"; then
      log_event "WARN" "main" "Force killing process tree (PID: ${pid})"
      kill_tree "$pid" KILL
    fi
  done

  # Cleanup stop flag
  rm -f "$STOP_FLAG_FILE"

  log_event "INFO" "main" "All processes stopped"
}

# Set up signal handlers
trap cleanup EXIT INT TERM HUP

# Remove any stale stop flag
rm -f "$STOP_FLAG_FILE"

# Initialize dev.log
echo "" >> "${DEV_LOG}"
log_event "INFO" "main" "========== Dev session started =========="

# Initialize action plugins before starting dev servers
echo "🔌 Initializing action plugins..."
if fullstack-cli action-plugin init; then
  echo "✅ Action plugins initialized"
else
  echo "⚠️  Action plugin initialization failed, continuing anyway..."
fi
echo ""

# Start server (cleanup orphan processes on SERVER_PORT)
start_supervised_process "server" "npm run dev:server" "${SERVER_PORT:-3000}"
SERVER_PID=$!
log_event "INFO" "server" "Supervisor started with PID ${SERVER_PID}"

# Start client (cleanup orphan processes on CLIENT_DEV_PORT)
start_supervised_process "client" "npm run dev:client" "${CLIENT_DEV_PORT:-8080}"
CLIENT_PID=$!
log_event "INFO" "client" "Supervisor started with PID ${CLIENT_PID}"

log_event "INFO" "main" "All processes started, monitoring..."
echo ""
echo "📋 Dev processes running. Press Ctrl+C to stop."
echo "📄 Logs: ${DEV_LOG}"
echo ""

# Wait for all background processes
wait
